spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: tuandung
    password: TuanDung@1207
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: inventory-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: com.exam.inventoryservice
        spring.json.value.default.type: com.exam.inventoryservice.OrderEvent
        spring.json.use.type.headers: false
server:
  port: 8082
