spring:
  application:
    name: notification-server

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: notification-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: com.exam.notificationserver
        spring.json.value.default.type: com.exam.notificationserver.OrderEvent
        spring.json.use.type.headers: false
server:
  port: 8083
